# OpenHands Configuration for DCypher Project
# This file provides context to OpenHands about the DCypher project structure and preferences

# NOTE: [versions] section is used by scripts/get_openhands_version.py for Docker builds
# This is NOT a valid OpenHands config section, but required by the build system
[versions]
openhands = "0.49.1"

[core]
# MAXIMIZE ITERATIONS FOR GROK-4 COMPLEX REASONING
max_iterations = 200

# Enable debugging for development
debug = true

# Cache directory for faster operations
cache_dir = "/tmp/dcypher_cache"

# File upload restrictions
file_uploads_restrict_file_types = true
file_uploads_allowed_extensions = [
  ".py",
  ".toml",
  ".md",
  ".txt",
  ".json",
  ".yaml",
  ".yml",
  ".sh",
  ".just",
  ".dockerfile",
  ".gitignore",
  ".zig",
]
file_uploads_max_file_size_mb = 50

[llm]
# GROK-4-0709 MAXIMUM PERFORMANCE CONFIGURATION
# Building the future with unlimited potential
model = "grok-4-0709"

# MAXIMUM CONTEXT UTILIZATION (256K tokens confirmed)
max_message_chars = 650000 # Support for massive cryptographic analysis
max_input_tokens = 256000  # Full 256K token context window
max_output_tokens = 25000  # Maximum output for comprehensive solutions

# OPTIMAL PERFORMANCE SETTINGS
temperature = 0.0     # Maximum precision for crypto work
top_p = 1.0
caching_prompt = true

# REAL OPENHANDS RETRY SETTINGS (no cost controls)
num_retries = 10       # Valid OpenHands option
retry_min_wait = 1     # Valid OpenHands option  
retry_max_wait = 120   # Valid OpenHands option
retry_multiplier = 2.0 # Valid OpenHands option
timeout = 600          # Extended timeout for complex reasoning

[agent]
# GROK-4 ENHANCED AGENT CONFIGURATION
# Enable function calling for better tool use
function_calling = true

# EXTENDED HISTORY FOR GROK-4'S 256K CONTEXT
# Disable truncation to utilize full context window
enable_history_truncation = false

# Enable all capabilities for maximum functionality
enable_browsing = true
enable_jupyter = true

[sandbox]
# Use Python 3.12 with Node.js for completeness
base_container_image = "nikolaik/python-nodejs:python3.12-nodejs22"

# EXTENDED TIMEOUT FOR GROK-4 COMPLEX REASONING
# Matches LLM timeout for cryptographic operations
timeout = 600

# Enable auto-linting after editing files
enable_auto_lint = true

# REAL OPENHANDS SANDBOX OPTIONS
use_host_network = true # Valid networking option

# Dependencies are now pre-installed in the Dockerfile.allhands
# runtime_extra_deps can be used for lighter, project-specific dependencies if needed

# Environment variables for the runtime
[sandbox.runtime_startup_env_vars]
PYTHONPATH = "/workspace/src"
UV_SYSTEM_PYTHON = "1"
PATH = "/usr/local/bin:$PATH"

# DCYPHER PROJECT OPTIMIZATION VARIABLES
OPENFHE_BUILD_TYPE = "Release" # Optimized crypto builds
OMP_NUM_THREADS = "16"         # Parallel processing for crypto
PYTHONOPTIMIZE = "2"           # Maximum Python optimization

[security]
# Enable confirmation mode for destructive operations
confirmation_mode = false

# All project-specific information moved to .openhands-instructions.md
# This config.toml now contains only valid OpenHands configuration options
