[project]
name = "dcypher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openfhe>=1.3.0.0.24.4",
    "pybind11>=2.13.6",
    "yowasp-yosys>=0.54.0.0.post930",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]
