# swaggerjacked with style and decomposed from https://github.com/open-quantum-safe/liboqs-python/blob/main/tests/test_kem.py
import oqs
import pytest

from .util.util import get_enabled_kems


@pytest.mark.parametrize("alg_name", get_enabled_kems())
def test_correctness(alg_name: str) -> None:
    """
    Tests that the shared secret generated by the client and server are the same.
    """
    with oqs.KeyEncapsulation(alg_name) as kem:
        public_key = kem.generate_keypair()
        ciphertext, shared_secret_server = kem.encap_secret(public_key)
        shared_secret_client = kem.decap_secret(ciphertext)
        assert shared_secret_client == shared_secret_server
